//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttachmentEncryption.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mm0205\\AttachmentEncryption\\Temp")]
        public string TempFolder {
            get {
                return ((string)(this["TempFolder"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoSending {
            get {
                return ((bool)(this["AutoSending"]));
            }
            set {
                this["AutoSending"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("attach_")]
        public string FileNamePrefix {
            get {
                return ((string)(this["FileNamePrefix"]));
            }
            set {
                this["FileNamePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[パスワードのお知らせ] ")]
        public string PasswordMailTitlePrefix {
            get {
                return ((string)(this["PasswordMailTitlePrefix"]));
            }
            set {
                this["PasswordMailTitlePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyyMMdd")]
        public string FileNameDateTimeFormat {
            get {
                return ((string)(this["FileNameDateTimeFormat"]));
            }
            set {
                this["FileNameDateTimeFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{{ for toName in tos }}{{ toName }}様\r\n{{ end }}\r\n\r\n{{ company }}の{{ user }}です\r\n先ほ" +
            "どのメールの添付ファイルのパスワードをお知らせします。\r\n\r\n件名: {{ subject }}\r\nパスワード: {{ password }}\r\n\r\nどうぞよろ" +
            "しくお願い致します。\r\n\r\n＃自社製のOutlookアドインによって、誤送信防止および\r\n自動添付ファイル暗号化を実現しています")]
        public string PasswordMailTemplate {
            get {
                return ((string)(this["PasswordMailTemplate"]));
            }
            set {
                this["PasswordMailTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[会社名]")]
        public string DefaultCompany {
            get {
                return ((string)(this["DefaultCompany"]));
            }
            set {
                this["DefaultCompany"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ユーザー名]")]
        public string DefaultUserName {
            get {
                return ((string)(this["DefaultUserName"]));
            }
            set {
                this["DefaultUserName"] = value;
            }
        }
    }
}
